
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 05 15:29:30 IST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LCBR = 10;
  public static final int LTE = 33;
  public static final int INTEGER = 25;
  public static final int SEMI = 9;
  public static final int CONTINUE = 15;
  public static final int INT = 24;
  public static final int MINUS = 3;
  public static final int STATIC = 41;
  public static final int LT = 32;
  public static final int LP = 27;
  public static final int COMMA = 14;
  public static final int CLASS = 6;
  public static final int RP = 39;
  public static final int PLUS = 2;
  public static final int MULTIPLY = 4;
  public static final int QUOTE = 49;
  public static final int ASSIGN = 11;
  public static final int IF = 23;
  public static final int THIS = 42;
  public static final int ID = 47;
  public static final int DOT = 16;
  public static final int EOF = 0;
  public static final int BOOLEAN = 12;
  public static final int RETURN = 38;
  public static final int RCBR = 37;
  public static final int LB = 7;
  public static final int LAND = 26;
  public static final int EQUAL = 17;
  public static final int TRUE = 43;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int RB = 8;
  public static final int LOR = 31;
  public static final int NULL = 36;
  public static final int NUMBER = 46;
  public static final int MOD = 34;
  public static final int BREAK = 13;
  public static final int VOID = 44;
  public static final int GTE = 22;
  public static final int ELSE = 19;
  public static final int WHILE = 45;
  public static final int NEQUAL = 35;
  public static final int CLASS_ID = 48;
  public static final int EXTENDS = 18;
  public static final int STRING = 40;
  public static final int LNEG = 30;
  public static final int FALSE = 20;
  public static final int GT = 21;
  public static final int LENGTH = 28;
}

